import type { SectionConfig } from "./sectionTypes";

// Mirrors "FORM 2: Shadow Teacher Daily Support & Intervention Record"
// section-for-section. Applies identically to every class/level --
// only the class name shown in the header changes.
export const SHADOW_TEACHER_RECORD_SECTIONS: SectionConfig[] = [
  {
    type: "ratingTable",
    key: "daily_support_summary",
    title: "Daily Support Summary",
    options: ["Independent", "Minimal Support", "Moderate Support", "Maximum Support"],
    rows: [
      { key: "academic_tasks", label: "Academic Tasks" },
      { key: "communication", label: "Communication" },
      { key: "behaviour_regulation", label: "Behaviour Regulation" },
      { key: "social_interaction", label: "Social Interaction" },
      { key: "personal_care", label: "Personal Care" },
      { key: "sensory_regulation", label: "Sensory Regulation" },
      { key: "transitions", label: "Transitions" },
    ],
  },
  {
    type: "ratingTable",
    key: "morning_arrival_support",
    title: "Morning Arrival Support",
    timeLabel: "8:00 AM – 8:30 AM",
    options: ["Independent", "Prompted", "Assisted"],
    rows: [
      { key: "enter_classroom", label: "Enter classroom" },
      { key: "greet_teacher", label: "Greet teacher" },
      { key: "arrange_belongings", label: "Arrange belongings" },
      { key: "follow_morning_routine", label: "Follow morning routine" },
      { key: "prepare_materials", label: "Prepare learning materials" },
    ],
  },
  {
    type: "checkboxList",
    key: "morning_arrival_interventions",
    title: "Intervention Provided (Morning Arrival)",
    options: [
      "Visual schedule",
      "Verbal prompting",
      "Physical guidance",
      "Demonstration/modeling",
      "Emotional reassurance",
      "Sensory regulation support",
    ],
  },
  {
    type: "freeTextFields",
    key: "morning_arrival_observation",
    title: "Morning Arrival Observation",
    fields: [{ key: "observation", label: "Observation" }],
  },
  {
    type: "ratingTable",
    key: "academic_support_skills",
    title: "Academic Support — Learning Skills",
    options: ["Independent", "Prompted", "Supported"],
    rows: [
      { key: "attended_lesson", label: "Attended lesson" },
      { key: "started_activity", label: "Started activity" },
      { key: "followed_instructions", label: "Followed instructions" },
      { key: "completed_task", label: "Completed task" },
      { key: "asked_for_help", label: "Asked for help" },
    ],
  },
  {
    type: "checkboxList",
    key: "academic_intervention_used",
    title: "Academic Intervention Used",
    options: [
      "Simplified instruction",
      "Visual support",
      "Task breakdown",
      "Extra processing time",
      "Hand-over-hand support",
      "Repetition",
      "Concrete materials",
    ],
  },
  {
    type: "freeTextFields",
    key: "academic_learner_response",
    title: "Academic Support — Learner Response",
    fields: [{ key: "response", label: "Learner Response" }],
  },
  {
    type: "ratingTable",
    key: "communication_support",
    title: "Communication Support Record",
    options: ["Achieved", "Developing", "Needs Support"],
    rows: [
      { key: "express_needs", label: "Express needs" },
      { key: "answer_questions", label: "Answer questions" },
      { key: "follow_instructions", label: "Follow instructions" },
      { key: "participate_conversation", label: "Participate in conversation" },
      { key: "communicate_emotions", label: "Communicate emotions" },
    ],
  },
  {
    type: "keyValueTable",
    key: "social_skills_support",
    title: "Social Skills Support",
    columns: ["Observation", "Intervention Used"],
    rows: [
      { key: "plays_with_peers", label: "Plays with peers" },
      { key: "shares_materials", label: "Shares materials" },
      { key: "takes_turns", label: "Takes turns" },
      { key: "maintains_behaviour", label: "Maintains appropriate behaviour" },
      { key: "resolves_conflict", label: "Resolves conflict" },
    ],
  },
  {
    type: "checkboxList",
    key: "social_skills_interventions",
    title: "Social Skills — Interventions Used",
    options: ["Social story", "Role play", "Peer support", "Emotional coaching", "Teacher modelling"],
  },
  {
    type: "keyValueTable",
    key: "sensory_regulation_support",
    title: "Sensory Regulation Support",
    columns: ["Observation", "Support Needed"],
    rows: [
      { key: "noise_sensitivity", label: "Noise sensitivity" },
      { key: "movement_needs", label: "Movement needs" },
      { key: "touch_sensitivity", label: "Touch sensitivity" },
      { key: "attention_regulation", label: "Attention regulation" },
      { key: "emotional_state", label: "Emotional state" },
    ],
  },
  {
    type: "checkboxList",
    key: "sensory_regulation_supports_used",
    title: "Sensory Regulation — Supports Used",
    options: [
      "Movement break",
      "Quiet area",
      "Deep pressure activity",
      "Breathing exercise",
      "Sensory tool",
      "Change of environment",
    ],
  },
  {
    type: "keyValueTable",
    key: "occupational_therapy_support",
    title: "Occupational Therapy Support Record",
    columns: ["Activity Provided", "Learner Response", "Next Step"],
    rows: [
      { key: "fine_motor", label: "Fine Motor" },
      { key: "gross_motor", label: "Gross Motor" },
      { key: "visual_motor", label: "Visual Motor" },
      { key: "motor_planning", label: "Motor Planning" },
    ],
  },
  {
    type: "ratingTable",
    key: "adaptive_skills_support",
    title: "Adaptive Skills Support",
    options: ["Independent", "Prompted", "Assisted"],
    rows: [
      { key: "eating", label: "Eating" },
      { key: "toileting", label: "Toileting" },
      { key: "hand_washing", label: "Hand washing" },
      { key: "organising_belongings", label: "Organising belongings" },
      { key: "following_routines", label: "Following routines" },
    ],
  },
  {
    type: "behaviourRecord",
    key: "behaviour_support_record",
    title: "Behaviour Support Record",
    behaviourOptions: ["Crying", "Avoidance", "Aggression", "Withdrawal", "Repetitive behaviour", "Distracted behaviour"],
    interventionOptions: ["Redirection", "Visual support", "Calm approach", "Choice offered", "Break provided"],
  },
  {
    type: "logTable",
    key: "daily_intervention_log",
    title: "Daily Intervention Log",
    columns: [
      { key: "time", label: "Time" },
      { key: "support_needed", label: "Support Needed" },
      { key: "intervention_provided", label: "Intervention Provided" },
      { key: "learner_response", label: "Learner Response" },
    ],
    minRows: 4,
  },
  {
    type: "radioWithNote",
    key: "independence_tracking",
    title: "Independence Tracking",
    options: [
      "Required less support than yesterday",
      "Maintained same support level",
      "Required more support",
    ],
    noteLabel: "Evidence",
  },
  {
    type: "freeTextFields",
    key: "end_of_day_report",
    title: "End-of-Day Shadow Teacher Report",
    fields: [
      { key: "success", label: "Child's Success Today" },
      { key: "challenge", label: "Main Challenge" },
      { key: "strategy", label: "Effective Strategy Used" },
      { key: "recommendation", label: "Recommendation for Tomorrow" },
    ],
  },
  {
    type: "checkboxList",
    key: "communication_record",
    title: "Communication Record",
    options: [
      "Progress shared with teacher",
      "Concern shared",
      "Classroom adjustment requested",
      "Daily parent update provided",
      "Home strategy suggested",
      "No communication required",
    ],
  },
];
