import type { Domain } from "./types";

export const FORM_B_DOMAINS: Domain[] = [
  {
    id: "b1_gross_motor",
    title: "Gross Motor and Mobility",
    type: "rating",
    items: [
      { id: "GM01", text: "Maintains supported or independent sitting posture for functional activities" },
      { id: "GM02", text: "Uses an effective floor-mobility pattern (e.g., crawling, scooting or other access method)" },
      { id: "GM03", text: "Walks or moves independently using their usual mobility method" },
      { id: "GM04", text: "Runs / moves quickly and safely when appropriate" },
      { id: "GM05", text: "Maintains balance during everyday movement and play" },
      { id: "GM06", text: "Participates in physical activities with appropriate access/support" },
      { id: "GM07", text: "Coordinates both sides of the body during movement tasks" },
    ],
    hasNarrative: true,
  },
  {
    id: "b2_fine_motor",
    title: "Fine Motor, Graphomotor and Access Skills",
    type: "rating",
    items: [
      { id: "FM01", text: "Uses a functional grasp for pencil, stylus or chosen writing tool" },
      { id: "FM02", text: "Uses scissors or an adapted cutting tool safely" },
      { id: "FM03", text: "Copies/draws shapes or visual forms at the child's current learning level" },
      { id: "FM04", text: "Produces letters, numbers or symbols using handwriting, typing or AAC access as appropriate" },
      { id: "FM05", text: "Builds/constructs with blocks or similar materials" },
      { id: "FM06", text: "Manipulates small objects, fasteners or learning materials" },
      { id: "FM07", text: "Coordinates visual attention and hand movement for classroom tasks" },
    ],
    hasNarrative: true,
  },
  {
    id: "b3_receptive_communication",
    title: "Receptive Communication",
    type: "rating",
    items: [
      { id: "RC01", text: "Responds to name or preferred attention cue in familiar settings" },
      { id: "RC02", text: "Understands familiar words, symbols, gestures or AAC messages" },
      { id: "RC03", text: "Understands one-step instructions when presented accessibly" },
      { id: "RC04", text: "Follows two- or multi-step directions with appropriate visual/verbal support" },
      { id: "RC05", text: "Understands basic concepts used in learning (e.g., first/next, same/different, before/after)" },
      { id: "RC06", text: "Indicates when a message or instruction is not understood" },
    ],
    hasNarrative: true,
  },
  {
    id: "b4_expressive_communication",
    title: "Expressive Communication and AAC",
    type: "rating",
    items: [
      { id: "EC01", text: "Communicates wants, needs, choices or refusals using speech, AAC, sign, gestures or other reliable mode" },
      { id: "EC02", text: "Combines words/symbols/gestures into messages appropriate to current communication level" },
      { id: "EC03", text: "Communicates emotions, discomfort or need for a break" },
      { id: "EC04", text: "Initiates communication for more than requesting (e.g., sharing, commenting, asking)" },
      { id: "EC05", text: "Maintains a reciprocal interaction for an increasing number of turns" },
      { id: "EC06", text: "Uses their communication system across more than one person/setting" },
      { id: "EC07", text: "Repairs a communication breakdown with support" },
    ],
    hasNarrative: true,
  },
  {
    id: "b5_social_communication",
    title: "Social Communication, Relationships and Participation",
    type: "rating",
    items: [
      { id: "SI01", text: "Uses a comfortable form of social attention/joint engagement (not necessarily eye contact)" },
      { id: "SI02", text: "Shares or exchanges materials when appropriate, with support as needed" },
      { id: "SI03", text: "Participates in cooperative or parallel play/activities" },
      { id: "SI04", text: "Initiates or responds to peer interaction in a personally comfortable way" },
      { id: "SI05", text: "Builds and maintains preferred relationships/friendships" },
      { id: "SI06", text: "Recognizes others' emotions or perspectives with available cues/support" },
      { id: "SI07", text: "Understands explicit social expectations and boundaries" },
      { id: "SI08", text: "Advocates for personal boundaries, consent, help or space" },
    ],
    hasNarrative: true,
  },
  {
    id: "b6_attention_executive_function",
    title: "Attention and Executive Function",
    type: "rating",
    items: [
      { id: "EF01", text: "Selects relevant information and filters distractions with available supports" },
      { id: "EF02", text: "Sustains attention long enough to engage meaningfully in a task" },
      { id: "EF03", text: "Shifts or divides attention between people/tasks when required" },
      { id: "EF04", text: "Starts tasks after instruction/cue" },
      { id: "EF05", text: "Plans the steps needed to complete a familiar task" },
      { id: "EF06", text: "Organizes materials, workspace and sequence" },
      { id: "EF07", text: "Solves everyday learning problems and tries alternatives" },
      { id: "EF08", text: "Pauses or uses a strategy before acting when safety/task demands require it" },
      { id: "EF09", text: "Shifts between tasks, rules or ideas with preparation/support" },
      { id: "EF10", text: "Completes tasks or returns to them after interruption" },
    ],
    hasNarrative: true,
  },
  {
    id: "b7_emotional_regulation",
    title: "Emotional Regulation and Self-Advocacy",
    type: "rating",
    items: [
      { id: "ER01", text: "Recognizes and labels/indicates internal emotional state using preferred communication" },
      { id: "ER02", text: "Communicates feelings, discomfort or distress in a way others can understand" },
      { id: "ER03", text: "Tolerates disappointment or an unexpected outcome with support" },
      { id: "ER04", text: "Transitions or adapts to changes when given appropriate preparation" },
      { id: "ER05", text: "Uses one or more calming/regulation strategies after frustration or overload" },
      { id: "ER06", text: "Returns to a learning-ready state after dysregulation with appropriate co-regulation" },
      { id: "ER07", text: "Requests a break, help, movement or sensory support before escalation when able" },
    ],
    hasNarrative: true,
  },
  {
    id: "b8_sensory_processing",
    title: "Sensory Processing and Environmental Access",
    type: "sensory",
    intro:
      "Sensory differences are not automatically deficits. Record the child's response, functional impact, preferred regulation strategy and whether the environment can be adjusted. Do not suppress harmless self-regulatory behaviour merely because it appears different.",
    items: [
      { id: "SP01", text: "Sound / loud or unpredictable noise" },
      { id: "SP02", text: "Light / visual intensity or clutter" },
      { id: "SP03", text: "Touch / clothing / textures / personal care" },
      { id: "SP04", text: "Movement / vestibular input" },
      { id: "SP05", text: "Body position / heavy work / proprioception" },
      { id: "SP06", text: "Oral / food texture / taste / smell" },
      { id: "SP07", text: "Interoception (hunger, pain, toileting, temperature)" },
      { id: "SP08", text: "Repetitive sensory or self-regulatory behaviours" },
      { id: "SP09", text: "Crowds / multi-sensory environments" },
    ],
    hasNarrative: true,
  },
  {
    id: "b9_adaptive_independence",
    title: "Adaptive, Independence and Daily Living Skills",
    type: "rating",
    items: [
      { id: "AD01", text: "Eats/drinks with the level of independence and safety expected for current access needs" },
      { id: "AD02", text: "Uses toilet routine with current level of support/accessibility" },
      { id: "AD03", text: "Dresses/undresses for daily routines with support as needed" },
      { id: "AD04", text: "Completes hygiene/self-care routines with support as needed" },
      { id: "AD05", text: "Manages personal belongings/materials" },
      { id: "AD06", text: "Follows familiar daily routines and schedules" },
      { id: "AD07", text: "Transitions between locations/activities using available supports" },
      { id: "AD08", text: "Recognizes and responds to basic safety cues" },
      { id: "AD09", text: "Requests help or communicates discomfort/unsafe situations" },
    ],
    hasNarrative: true,
  },
  {
    id: "b10_cognitive_learning",
    title: "Cognitive and Learning Behaviours",
    type: "rating",
    items: [
      { id: "CL01", text: "Remembers recently presented information long enough to use it in a task" },
      { id: "CL02", text: "Matches, sorts, categorizes or identifies patterns at current learning level" },
      { id: "CL03", text: "Uses problem-solving strategies and learns from feedback" },
      { id: "CL04", text: "Generalizes a learned skill to a different person, material or setting" },
      { id: "CL05", text: "Persists with a task when appropriately challenging" },
      { id: "CL06", text: "Learns from modelling/demonstration" },
      { id: "CL07", text: "Learns from visual, spoken, tactile, movement or technology supports when matched to task" },
    ],
    hasNarrative: true,
  },
  {
    id: "b11_academic_baseline",
    title: "Academic / Pre-Academic Functional Baseline",
    type: "baseline",
    intro:
      "Use only the rows relevant to the child's current educational stage. Record actual baseline evidence (e.g., \"reads 18/25 CVC words independently\"), not broad labels such as \"poor reading.\"",
    items: [
      { id: "AC01", text: "Early literacy / reading" },
      { id: "AC02", text: "Written expression / alternative written output" },
      { id: "AC03", text: "Early numeracy / mathematics" },
      { id: "AC04", text: "Concept knowledge / subject learning" },
      { id: "AC05", text: "Work completion / classroom participation" },
      { id: "AC06", text: "Assessment access / demonstration of knowledge" },
      { id: "AC07", text: "Technology / digital learning access" },
    ],
    hasNarrative: true,
  },
  {
    id: "b12_neurodevelopmental_observation",
    title: "Neurodevelopmental Observation Profile — NOT A DIAGNOSIS",
    type: "neurodevelopmental",
    intro:
      "This section captures patterns that may affect access, learning or participation. Do not use the checklist to infer or label a diagnosis. Record frequency, context and functional impact. Harmless differences should not become intervention targets solely for appearing atypical.",
    items: [
      { id: "NO01", text: "Attention is easily pulled away by competing stimuli" },
      { id: "NO02", text: "Task completion is difficult without repeated prompting/support" },
      { id: "NO03", text: "Needs instructions repeated, simplified or made visual" },
      { id: "NO04", text: "High movement need / frequent movement supports regulation" },
      { id: "NO05", text: "Waiting or turn-taking is difficult in some contexts" },
      { id: "NO06", text: "Strong preference for predictability/routine" },
      { id: "NO07", text: "Repetitive movements, speech, play or interests are observed" },
      { id: "NO08", text: "Sensory differences significantly shape participation" },
      { id: "NO09", text: "Highly focused/intense interests influence motivation or flexibility" },
      { id: "NO10", text: "Communication may differ by setting, familiarity or stress level" },
    ],
    hasNarrative: false,
  },
  {
    id: "b13_learning_access_preferences",
    title: "Learning Access Preferences and Effective Supports",
    type: "keyvalue",
    intro:
      "Record what improves access and performance. Do not treat \"learning styles\" as fixed traits; the same learner may benefit from different modalities depending on the task.",
    keyValueFields: [
      {
        key: "visual_supports",
        label: "Visual supports",
        type: "checklist",
        options: ["Visual schedule", "Pictures/icons", "Written steps", "Demonstration", "Graphic organizer"],
      },
      {
        key: "auditory_language_supports",
        label: "Auditory / language supports",
        type: "checklist",
        options: ["Short spoken directions", "Repetition", "Read-aloud", "Reduced verbal load", "Extra processing time"],
      },
      {
        key: "movement_hands_on",
        label: "Movement / hands-on",
        type: "checklist",
        options: ["Movement breaks", "Manipulatives", "Role play", "Hands-on practice", "Standing/flexible seating"],
      },
      {
        key: "technology_access",
        label: "Technology / assistive access",
        type: "checklist",
        options: ["Tablet/computer", "Text-to-speech", "Speech-to-text", "AAC", "Alternative keyboard/input"],
      },
      {
        key: "task_structure",
        label: "Task structure",
        type: "checklist",
        options: ["First-then", "Timer", "Choice of task order", "Chunking", "Reduced quantity", "Preview of changes"],
      },
      {
        key: "environment",
        label: "Environment",
        type: "checklist",
        options: ["Quiet area", "Reduced visual clutter", "Noise reduction", "Predictable seating", "Sensory tools"],
      },
      {
        key: "motivation_engagement",
        label: "Motivation / engagement (interests, preferred activities, praise/feedback style, tangible/non-tangible reinforcers if appropriate)",
        type: "textarea",
      },
      {
        key: "supports_that_do_not_help",
        label: "Supports that do NOT help / increase stress",
        type: "textarea",
      },
    ],
    hasNarrative: false,
  },
  {
    id: "b14_strengths_interests_motivators",
    title: "Strengths, Interests and Motivators",
    type: "keyvalue",
    keyValueFields: [
      {
        key: "strengths_observed",
        label: "Strengths observed",
        type: "checklist",
        options: [
          "Creativity",
          "Memory",
          "Problem-solving",
          "Leadership",
          "Artistic ability",
          "Musical ability",
          "Technology skills",
          "Empathy/caring",
          "Curiosity",
          "Persistence",
          "Other",
        ],
      },
      { key: "favourite_activities", label: "Favourite activities", type: "text" },
      { key: "favourite_subjects_topics", label: "Favourite subjects/topics", type: "text" },
      {
        key: "special_intense_interests",
        label: "Special/intense interests (include how they can support learning)",
        type: "textarea",
      },
      {
        key: "motivators",
        label: "Motivators (people, activities, choices, preferred feedback, goals)",
        type: "textarea",
      },
      { key: "emerging_talents_aspirations", label: "Emerging talents / aspirations", type: "text" },
    ],
    hasNarrative: false,
  },
  {
    id: "b15_priority_support_needs",
    title: "Priority Support Needs",
    type: "keyvalue",
    keyValueFields: [
      {
        key: "priority_areas",
        label: "Select relevant areas",
        type: "checklist",
        options: [
          "Attention/executive function",
          "Communication",
          "Social participation",
          "Emotional regulation",
          "Sensory access",
          "Motor/mobility",
          "Academic learning",
          "Adaptive/independence",
          "Confidence/self-advocacy",
          "Assistive technology",
          "Other",
        ],
      },
      { key: "top_priority_1", label: "Top Priority 1 (need + why it matters functionally)", type: "textarea" },
      { key: "top_priority_2", label: "Top Priority 2 (need + why it matters functionally)", type: "textarea" },
      { key: "top_priority_3", label: "Top Priority 3 (need + why it matters functionally)", type: "textarea" },
    ],
    hasNarrative: false,
  },
  {
    id: "b16_narrative",
    title: "Parent / Teacher / Therapist Observation Narrative",
    type: "keyvalue",
    keyValueFields: [
      { key: "what_makes_unique", label: "What makes this child unique?", type: "textarea" },
      {
        key: "challenges_barriers",
        label: "What challenges or barriers does the child experience?",
        type: "textarea",
      },
      { key: "what_support_worked", label: "What support has worked before?", type: "textarea" },
      {
        key: "overload_triggers",
        label: "What tends to trigger overload, withdrawal or escalation?",
        type: "textarea",
      },
      {
        key: "communicates_no_stop",
        label: "How does the child communicate \"no,\" \"stop,\" pain, fatigue or need for a break?",
        type: "textarea",
      },
      {
        key: "successful_school_day",
        label: "What would a successful school day look like for this child?",
        type: "textarea",
      },
    ],
    hasNarrative: false,
  },
];
