import type { StepConfig } from "./types";

export const PART_A_STEPS: StepConfig[] = [
  {
    id: "A1",
    title: "Child / Learner Profile",
    fields: [
      { key: "legal_name", label: "Legal Name", type: "text", required: true },
      { key: "preferred_name", label: "Preferred Name", type: "text" },
      { key: "date_of_birth", label: "Date of Birth", type: "date", required: true },
      { key: "sex_gender", label: "Sex / Gender", type: "text", helpText: "Optional" },
      { key: "pronouns", label: "Pronouns", type: "text", helpText: "Optional" },
      { key: "primary_languages", label: "Primary Language(s)", type: "text" },
      { key: "communication_modes", label: "Communication Mode(s)", type: "text", helpText: "e.g. Speech, AAC, Sign, Gestures, Mixed, Other" },
      { key: "current_school", label: "Current School / Centre", type: "text" },
      { key: "grade_class_level", label: "Current Grade / Class / Level (if previously enrolled elsewhere)", type: "text" },
      { key: "admission_programme", label: "Admission Programme", type: "text" },
      { key: "expected_start_date", label: "Expected Start Date", type: "date" },
    ],
  },
  {
    id: "A2",
    title: "Parent / Guardian and Emergency Contact",
    fields: [
      {
        key: "primary_guardian",
        label: "Primary Parent/Guardian",
        type: "compound",
        subFields: [
          { key: "full_name", label: "Full Name" },
          { key: "relationship", label: "Relationship" },
          { key: "phone", label: "Phone" },
          { key: "email", label: "Email" },
          { key: "preferred_contact", label: "Preferred Contact Method" },
        ],
      },
      {
        key: "secondary_guardian",
        label: "Secondary Parent/Guardian",
        type: "compound",
        subFields: [
          { key: "full_name", label: "Full Name" },
          { key: "relationship", label: "Relationship" },
          { key: "phone", label: "Phone" },
          { key: "email", label: "Email" },
          { key: "preferred_contact", label: "Preferred Contact Method" },
        ],
      },
      { key: "home_address", label: "Home Locality / Address", type: "textarea", helpText: "Collect only to the level required" },
      {
        key: "emergency_contact",
        label: "Emergency Contact",
        type: "compound",
        subFields: [
          { key: "name", label: "Name" },
          { key: "relationship", label: "Relationship" },
          { key: "phone", label: "Phone" },
        ],
      },
      { key: "authorized_pickup", label: "Authorized Pickup / Responsible Adult(s)", type: "textarea" },
      { key: "family_accessibility_needs", label: "Language / Accessibility Needs of Family", type: "textarea", helpText: "Interpreter, easy-read, communication support, other" },
    ],
  },
  {
    id: "A3",
    title: "Family Priorities and Learner Voice",
    fields: [
      { key: "main_concerns", label: "Parent/Guardian Main Concerns", type: "textarea", helpText: "What is making learning, communication, participation or daily routines difficult?" },
      { key: "family_priorities", label: "Family Priorities", type: "textarea", helpText: "The 3 most important changes or skills the family wants to support" },
      { key: "learner_voice", label: "Learner Preferences / Voice", type: "textarea", helpText: "What does the child say, show or choose about school, learning, friends, routines and goals?" },
      { key: "child_enjoys", label: "What the Child Enjoys", type: "textarea", helpText: "Activities, people, topics, routines, places, objects, technology" },
      { key: "child_avoids", label: "What the Child Avoids or Finds Difficult", type: "textarea", helpText: "Situations, demands, sensory conditions, transitions, communication contexts" },
    ],
  },
  {
    id: "A4",
    title: "Educational History",
    fields: [
      { key: "current_placement", label: "Current Educational Placement", type: "select", options: ["Preschool", "Mainstream", "Inclusive", "Specialised", "Home-based", "Other"] },
      { key: "previous_schools", label: "Previous Schools / Centres", type: "textarea", helpText: "Name(s), dates, reason for transition if relevant" },
      { key: "attendance_pattern", label: "Attendance Pattern", type: "select", options: ["Regular", "Variable", "Significant absence"] },
      { key: "attendance_notes", label: "Attendance Notes", type: "textarea" },
      { key: "previous_iep", label: "Previous IEP / Learning Plan", type: "radio", options: ["No", "Yes"] },
      { key: "previous_iep_summary", label: "Previous IEP Summary (if yes)", type: "textarea" },
      { key: "current_classroom_supports", label: "Current Classroom Supports", type: "textarea", helpText: "Visual supports, seating, reduced workload, movement breaks, AAC, extra time, adult support, other" },
      { key: "academic_strengths", label: "Academic Strengths", type: "textarea", helpText: "Literacy, numeracy, memory, problem-solving, creativity, technology, other" },
      { key: "academic_concerns", label: "Academic / Participation Concerns", type: "textarea", helpText: "Observable areas of difficulty and contexts" },
      { key: "school_family_priorities", label: "School-Family Priorities Already Identified", type: "textarea" },
    ],
  },
  {
    id: "A5",
    title: "Developmental, Health and Safety Information",
    intro: "Only information necessary for education, participation, accessibility or safety. This form does not establish a diagnosis.",
    fields: [
      { key: "pregnancy_gestation", label: "Pregnancy / Gestation", type: "select", options: ["Full-term", "Preterm", "Unknown", "Prefer not to say"] },
      { key: "birth_type", label: "Birth Type / Events", type: "select", options: ["Vaginal", "Caesarean", "Other", "Unknown"] },
      { key: "birth_notes", label: "Birth Complications (if relevant)", type: "textarea" },
      { key: "nicu_admission", label: "NICU / Neonatal Admission", type: "radio", options: ["No", "Yes", "Unknown"] },
      { key: "feeding_history", label: "Feeding History", type: "select", options: ["No known difficulty", "Difficulty reported", "Current support"] },
      { key: "hearing_vision", label: "Hearing / Vision", type: "select", options: ["No known concern", "Concern", "Uses support"] },
      { key: "sleep_patterns", label: "Sleep Patterns Affecting Learning", type: "radio", options: ["No", "Yes"] },
      { key: "sleep_notes", label: "Sleep Pattern Notes", type: "textarea" },
      { key: "allergies", label: "Allergies / Dietary Safety Needs", type: "radio", options: ["No", "Yes"] },
      { key: "allergies_notes", label: "Allergy Triggers / Emergency Action", type: "textarea" },
      { key: "medication", label: "Medication Relevant to School Day", type: "radio", options: ["None reported", "Yes"] },
      { key: "medication_notes", label: "Medication Details", type: "textarea", helpText: "Name, timing, administration plan — optional to provide" },
      { key: "medical_safety_plan", label: "Medical / Neurological Safety Plan", type: "textarea", helpText: "Seizure plan, mobility plan, other" },
      {
        key: "documented_diagnosis",
        label: "Documented Diagnosis/Condition, if any",
        type: "compound",
        subFields: [
          { key: "name", label: "Name" },
          { key: "professional_service", label: "Professional / Service" },
          { key: "date", label: "Date" },
          { key: "documentation_available", label: "Documentation Available?" },
        ],
      },
      { key: "developmental_regression", label: "Developmental Regression / Loss of Skill", type: "radio", options: ["No", "Yes", "Unknown"] },
      { key: "regression_notes", label: "Regression Details", type: "textarea", helpText: "Skill, approximate age and context" },
    ],
  },
  {
    id: "A6",
    title: "Developmental Milestones and Daily Function",
    fields: [
      { key: "sat_independently", label: "Sat Independently", type: "text", helpText: "Age / Unknown / Not applicable" },
      { key: "crawled_mobility", label: "Crawled or Alternative Mobility Stage", type: "text", helpText: "Age / pattern / Unknown" },
      { key: "walked_independently", label: "Walked Independently", type: "text", helpText: "Age / current mobility support if any" },
      { key: "first_words", label: "First Meaningful Words / Communication", type: "text", helpText: "Age / modality / Unknown" },
      { key: "combined_words", label: "Combined Words / Phrases", type: "text", helpText: "Age / modality / Unknown" },
      { key: "toileting", label: "Toileting Independence", type: "select", options: ["Independent", "Emerging", "Requires support", "Not applicable"] },
      { key: "eating_feeding", label: "Eating / Feeding Independence", type: "select", options: ["Independent", "Emerging", "Requires support", "Uses adaptive support"] },
      { key: "dressing_hygiene", label: "Dressing / Hygiene", type: "select", options: ["Independent", "Emerging", "Requires support"] },
      { key: "current_mobility", label: "Current Mobility", type: "select", options: ["Independent", "Assistive device", "Physical support", "Other"] },
    ],
  },
  {
    id: "A7",
    title: "Current Services, Supports and Professionals",
    fields: [
      {
        key: "speech_language_support",
        label: "Speech-Language / Communication Support",
        type: "compound",
        subFields: [
          { key: "provider", label: "Provider" },
          { key: "frequency", label: "Frequency" },
          { key: "targets", label: "Current Targets" },
        ],
      },
      {
        key: "ot_support",
        label: "Occupational Therapy / Sensory-Motor Support",
        type: "compound",
        subFields: [
          { key: "provider", label: "Provider" },
          { key: "frequency", label: "Frequency" },
          { key: "targets", label: "Current Targets" },
        ],
      },
      {
        key: "physio_support",
        label: "Physiotherapy / Mobility Support",
        type: "compound",
        subFields: [
          { key: "provider", label: "Provider" },
          { key: "frequency", label: "Frequency" },
          { key: "targets", label: "Current Targets" },
        ],
      },
      {
        key: "learning_support",
        label: "Learning / Special Education Support",
        type: "compound",
        subFields: [
          { key: "provider", label: "Provider" },
          { key: "frequency", label: "Frequency" },
          { key: "targets", label: "Current Targets" },
        ],
      },
      {
        key: "counselling_support",
        label: "Counselling / Emotional Wellbeing Support",
        type: "compound",
        subFields: [
          { key: "provider", label: "Provider" },
          { key: "frequency", label: "Frequency" },
          { key: "targets", label: "Current Targets" },
        ],
      },
      {
        key: "other_support",
        label: "Other Intervention / Specialist Support",
        type: "compound",
        subFields: [
          { key: "type", label: "Type" },
          { key: "provider", label: "Provider" },
          { key: "frequency", label: "Frequency" },
          { key: "targets", label: "Targets" },
        ],
      },
      {
        key: "assistive_technology",
        label: "Assistive Technology / AAC",
        type: "compound",
        subFields: [
          { key: "device_system", label: "Device/System" },
          { key: "access_method", label: "Access Method" },
          { key: "where_used", label: "Where Used" },
          { key: "partners_trained", label: "Communication Partners Trained?" },
        ],
      },
    ],
  },
  {
    id: "A9",
    title: "Consent and Data Use",
    fields: [
      { key: "c1_data_collection", label: "I consent to collection and storage of the educational/developmental information in this form for individualized education planning.", type: "radio", options: ["Yes", "No"], required: true },
      { key: "c2_ai_processing", label: "I consent to AI-assisted processing of this information to generate a draft IEP for human review.", type: "radio", options: ["Yes", "No"], required: true },
      { key: "c3_ai_not_diagnosis", label: "I understand AI output is not a diagnosis and must be reviewed by the education/support team.", type: "radio", options: ["Acknowledged"], required: true },
      { key: "c4_professional_sharing", label: "I consent to relevant information being shared with named professionals involved in the child's education/support.", type: "radio", options: ["Yes", "No"], required: true },
      { key: "c5_correction_rights", label: "I understand I may request correction/update of information and may ask how the data was used in the IEP draft.", type: "radio", options: ["Acknowledged"], required: true },
      { key: "guardian_name", label: "Parent/Guardian Name", type: "text", required: true },
      { key: "signature", label: "Signature (type your full name to sign)", type: "text", required: true },
      { key: "signature_date", label: "Date", type: "date", required: true },
    ],
  },
];
