import type { SectionConfig } from "./sectionTypes";

// Mirrors "NATM Daily Teacher Observation Form (8:00 AM - 3:00 PM)"
// section-for-section. Applies identically to every class/level --
// only the class name shown in the header changes.
export const CLASS_TEACHER_OBSERVATION_SECTIONS: SectionConfig[] = [
  {
    type: "ratingTable",
    key: "daily_functional_summary",
    title: "Daily Functional Summary",
    options: ["Excellent", "Developing", "Needs Support"],
    rows: [
      { key: "attention", label: "Attention" },
      { key: "communication", label: "Communication" },
      { key: "social_interaction", label: "Social Interaction" },
      { key: "emotional_regulation", label: "Emotional Regulation" },
      { key: "independence", label: "Independence" },
      { key: "academic_participation", label: "Academic Participation" },
      { key: "motor_skills", label: "Motor Skills" },
    ],
  },
  {
    type: "ratingTable",
    key: "arrival_routine",
    title: "Arrival, Transition & Morning Routine",
    timeLabel: "8:00 AM – 8:30 AM",
    options: ["Independent", "Prompted", "Full Support"],
    rows: [
      { key: "enters_calmly", label: "Enters classroom calmly" },
      { key: "greets", label: "Greets teacher and peers" },
      { key: "keeps_organised", label: "Keeps belongings organised" },
      { key: "follows_routine", label: "Follows morning routine" },
      { key: "settles_in", label: "Settles into learning environment" },
    ],
  },
  {
    type: "ratingTable",
    key: "morning_circle",
    title: "Morning Circle / Assembly / Emotional Check-In",
    timeLabel: "8:30 AM – 9:00 AM",
    options: ["Independent", "Prompted", "Full Support"],
    rows: [
      { key: "identifies_emotions", label: "Identifies emotions" },
      { key: "participates_discussion", label: "Participates in discussion" },
      { key: "listens", label: "Listens to others" },
      { key: "waits_turn", label: "Waits for turn" },
      { key: "expresses_needs", label: "Expresses needs appropriately" },
    ],
  },
  {
    type: "ratingTable",
    key: "break_time",
    title: "Break Time / Feeding / Social Interaction",
    timeLabel: "10:00 AM – 10:30 AM",
    options: ["Independent", "Prompted", "Full Support"],
    rows: [
      { key: "opens_lunch", label: "Opens lunch container" },
      { key: "eats_appropriately", label: "Eats appropriately" },
      { key: "cleans_area", label: "Cleans personal area" },
      { key: "interacts_peers", label: "Interacts with peers" },
      { key: "shares_materials", label: "Shares materials" },
    ],
  },
  {
    type: "ratingTable",
    key: "physical_motor",
    title: "Physical & Motor Development",
    timeLabel: "11:30 AM – 12:00 PM",
    options: ["Independent", "Prompted", "Full Support"],
    rows: [
      { key: "balance", label: "Balance" },
      { key: "coordination", label: "Coordination" },
      { key: "running_jumping", label: "Running and jumping" },
      { key: "team_participation", label: "Team participation" },
      { key: "follows_safety", label: "Follows safety instructions" },
    ],
  },
  {
    type: "ratingTable",
    key: "creative_practical",
    title: "Creative / Practical Learning Activities",
    timeLabel: "1:00 PM – 2:00 PM",
    options: ["Independent", "Prompted", "Full Support"],
    rows: [
      { key: "shows_creativity", label: "Shows creativity" },
      { key: "follows_steps", label: "Follows steps" },
      { key: "uses_materials_safely", label: "Uses materials safely" },
      { key: "works_independently", label: "Works independently" },
      { key: "shares_ideas", label: "Shares ideas" },
    ],
  },
  {
    type: "ratingTable",
    key: "closing_routine",
    title: "Closing Routine & Departure",
    timeLabel: "2:30 PM – 3:00 PM",
    options: ["Independent", "Prompted", "Full Support"],
    rows: [
      { key: "packs_bag", label: "Packs bag" },
      { key: "waits_calmly", label: "Waits calmly" },
      { key: "follows_dismissal", label: "Follows dismissal routine" },
      { key: "says_goodbye", label: "Says goodbye appropriately" },
    ],
  },
  {
    type: "ratingTable",
    key: "academic_learning",
    title: "Academic Learning Observation",
    options: ["Independent", "Prompted", "Support Needed"],
    rows: [
      { key: "attends_instruction", label: "Attends to instruction" },
      { key: "begins_task", label: "Begins task independently" },
      { key: "completes_activity", label: "Completes activity" },
      { key: "demonstrates_understanding", label: "Demonstrates understanding" },
      { key: "problem_solving", label: "Problem solving" },
      { key: "memory_recall", label: "Memory recall" },
      { key: "following_instructions", label: "Following instructions" },
    ],
  },
  {
    type: "checkboxList",
    key: "fine_motor_observation",
    title: "Fine Motor Observation",
    options: [
      "Uses pencil correctly",
      "Writes within lines",
      "Copies from board",
      "Uses learning materials appropriately",
    ],
  },
  {
    type: "checkboxList",
    key: "sensory_observation",
    title: "Sensory Observation",
    options: [
      "Maintains sitting position",
      "Requires movement break",
      "Sensitive to noise",
      "Distracted by environment",
      "Uses sensory strategy successfully",
    ],
  },
  {
    type: "keyValueTable",
    key: "occupational_therapy",
    title: "Occupational Therapy Observation",
    columns: ["Observation", "Support Required"],
    rows: [
      { key: "fine_motor_skills", label: "Fine Motor Skills" },
      { key: "gross_motor_skills", label: "Gross Motor Skills" },
      { key: "visual_motor_integration", label: "Visual Motor Integration" },
      { key: "motor_planning", label: "Motor Planning" },
      { key: "sensory_regulation", label: "Sensory Regulation" },
    ],
  },
  {
    type: "ratingTable",
    key: "adaptive_skills",
    title: "Adaptive Skills Record",
    options: ["Independent", "Prompt", "Assistance"],
    rows: [
      { key: "toileting_routine", label: "Toileting routine" },
      { key: "hand_washing", label: "Hand washing" },
      { key: "eating", label: "Eating" },
      { key: "personal_hygiene", label: "Personal hygiene" },
      { key: "packing_materials", label: "Packing materials" },
    ],
  },
  {
    type: "behaviourRecord",
    key: "abc_behaviour_record",
    title: "ABC Behaviour Record",
    behaviourOptions: ["Crying", "Withdrawal", "Aggression", "Avoidance", "Inattention", "Other"],
    hasTeacherResponse: true,
  },
  {
    type: "logTable",
    key: "daily_intervention_record",
    title: "Daily Intervention Record",
    columns: [
      { key: "time", label: "Time" },
      { key: "support_provided", label: "Support Provided" },
      { key: "learner_response", label: "Learner Response" },
    ],
    minRows: 3,
  },
  {
    type: "freeTextFields",
    key: "end_of_day_summary",
    title: "End of Day Summary",
    fields: [
      { key: "strength", label: "Child's strength today" },
      { key: "challenge", label: "Challenge observed" },
      { key: "strategy", label: "Strategy that worked" },
      { key: "recommendation", label: "Recommendation for tomorrow" },
    ],
  },
  {
    type: "checkboxList",
    key: "parent_communication",
    title: "Parent Communication",
    options: ["No concern", "Home practice recommended", "Parent discussion required"],
  },
];
